name: Send email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo contents
        uses: actions/checkout@v2
         
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
         
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send newsletter
        run: |
          python infrequent.py
        env:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         
